site_name: regexr
repo_url: https://github.com/pwwang/regexr
repo_name: pwwang/regexr
theme:
    name: 'material'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
plugins:
    - search # necessary for search to work
    - mkapi
extra_css:
    - style.css
nav:
    - 'Home': 'index.md'
    - 'API': mkapi/api/regexr
    - 'Change log': 'CHANGELOG.md'
